[project]
name = "sesac-3-project2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "colorama>=0.4.6",
    "langchain>=1.4.2",
    "langchain-openai>=1.6.3",
    "langgraph>=1.2.12",
    "langgraph-cli[inmem]>=0.4.31",
]
